### ISSUE TITLE
No such file or directory: '/usr/local/bin/../tools/pebble/PebbleEmulator.py'

### ISSUE THREAD

**Issue by jneubrand** [cpfair/pebble-recorder#1]
```
INFO:pebble_recorder:Recompiling app with backlight override...
INFO:pebble_recorder:Starting patched emulator
Traceback (most recent call last):
  File "/Users/johannes/Documents/pebble-misc/pebble-recorder/pebble-recorder", line 4, in <module>
    run("basalt" if len(sys.argv) < 2 else sys.argv[1])
  File "/Users/johannes/Documents/pebble-misc/pebble-recorder/pebble_recorder.py", line 207, in run
    PebbleRecorder().run(platform)
  File "/Users/johannes/Documents/pebble-misc/pebble-recorder/pebble_recorder.py", line 203, in run
    self.boot_emulator()
  File "/Users/johannes/Documents/pebble-misc/pebble-recorder/pebble_recorder.py", line 159, in boot_emulator
    with FilePatch(self.sdk_pebble_emulator_module, lambda x: x.replace('cmdline = [qemu_bin]', "cmdline = [qemu_bin, \"-qmp\", \"unix:%s,server,nowait\"]\n        os.setpgrp()" % self._qmp_socket_path)):
  File "/Users/johannes/Documents/pebble-misc/pebble-recorder/pebble_recorder.py", line 28, in __enter__
    shutil.copy(self.path, self.path + ".pebble-recorder-bak")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/usr/local/bin/../tools/pebble/PebbleEmulator.py'
```

**Comment by cpfair** [comment]
The library doesn't work on 4.x of the SDK - you'd need to update the paths used for automatic file patching.
